import streamlit as st
from models.embeddings import get_embeddings
from utils.retrieve import retrieve_docs
from utils.web_search import web_search
from models.llm import get_chat_model

st.title("NeoStats AI Engineer Assistant")

# Initialize session chat history
if "history" not in st.session_state:
    st.session_state.history = []

# Dummy local documents
docs = [
    "NeoStats provides AI-powered analytics for IT and engineering teams.",
    "Streamlit allows fast deployment of AI, ML, and data applications.",
    "RAG integrates local documents with LLMs to provide contextual answers."
]

# Generate embeddings once
doc_embeddings = get_embeddings(docs)

# UI Controls
mode = st.radio("Response Mode", ["Concise", "Detailed"])
query = st.text_input("Enter your question:")

# Load model (dummy or real LLM)
llm = get_chat_model()

def generate_answer(query, context, mode):
    """Generates response using the model or dummy fallback."""
    if llm:
        # Real Groq Model Response
        prompt = f"""
User Query: {query}
Context: {context}
Response Mode: {mode}

Write a helpful answer.
"""
        response = llm(prompt)
        return response
    else:
        # Dummy fallback
        if mode == "Concise":
            return f"[Concise Answer] User Query: {query}\nContext: {context[:140]}..."
        else:
            return f"[Detailed Answer] User Query: {query}\nContext: {context}\n\nThis is a detailed response generated by the dummy LLM."

if st.button("Ask"):
    try:
        # RAG Search
        top_docs = retrieve_docs(query, docs, doc_embeddings)

        if top_docs:
            context = "\n".join(top_docs)
        else:
            context = "\n".join(web_search(query))

        # Generate final response
        answer = generate_answer(query, context, mode)

        # Save to session history
        st.session_state.history.append(("You", query))
        st.session_state.history.append(("Assistant", answer))

    except Exception as e:
        st.error(f"Something went wrong: {e}")

# Show Chat History
st.subheader("Chat History")
for role, message in st.session_state.history:
    st.write(f"**{role}:** {message}")
