# models/llm.py

def get_chat_model():
    """Dummy LLM that works without API keys."""
    def model(prompt, mode="Concise"):
        if mode == "Concise":
            return f"[Concise Answer]\n{prompt[:180]}..."
        else:
            return f"[Detailed Answer]\n{prompt}\n\nThis is a detailed response generated by the dummy LLM."
    return model
